#測試python 檔案

name: 執行Python測試
on: 
  push:
    branches:
    - main #當推送到main 分支,進行測試
  pull_request:
    branches:
      -main #當拉取請求到 main 分支,進行測試

jobs: 
  runTest:   
    runs-on: ubuntu-latest  #在Ubuntu 虛擬機器上,進行測試
    steps:
      - name : 檢測程式碼
        uses: actions/checkout@v4

      - name: 設置python環境
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'  #使用python 3 的版本          

      - name: 安裝要使用的套件
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  #安裝 requirements.txt 中的套件
          
      - name: 執行Unit0204Dict.py
        run: |
          python Unit0204Dict.py  #執行 Unit0204Dict.py
          


        
